// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/chubin518/kestrel-layout-basic/internal/app"
	"github.com/chubin518/kestrel-layout-basic/internal/handler"
	"github.com/chubin518/kestrel-layout-basic/internal/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func newApp() (*app.App, error) {
	hook := app.NewAppHook()
	userService := service.NewUserService()
	userHandler := handler.NewUserHandler(userService)
	routes := app.NewRoutes(userHandler)
	appApp := app.NewApp(hook, routes)
	return appApp, nil
}

// wire.go:

var ServiceSet = wire.NewSet(service.NewUserService)

var HandlerSet = wire.NewSet(handler.NewUserHandler)

var RoutesSet = wire.NewSet(app.NewRoutes)

var HooksSet = wire.NewSet(app.NewAppHook)

var AppSet = wire.NewSet(app.NewApp)
